### ISSUE TITLE
How to insert unescaped text?

### ISSUE THREAD

**Issue by finalclass** [mhanberg/temple#10]
Is it possible to insert unescaped text in the template?

Please check this stackoverflow issue for the expanded question: https://stackoverflow.com/questions/57331864/how-to-insert-unescaped-text-in-elixir-temple-template

**Comment by finalclass** [comment]
OK, nevermind. I've found a way to do that:
```
text @some_text_that_we_dont_want_to_escape
```

**Comment by mhanberg** [comment]
If you would like to emit raw content into the HTML, I would use the `partial` macro from Temple and `Phoenix.HTML.raw` from phoenix_html.

```elixir
div do
  partial Phoenix.HTML.raw("<div>Unescaped content!</div>")
  # alternative approach, since all Phoenix.HTML.raw does is mark it as :safe
  partial {:safe, "<div>Unescaped content!</div>"}
end
```

>OK, I've found a way to do that
>script @some_text_that_we_dont_want_to_escape.

I think that this is a bug actually. It should be escaping content passed to a tag. In this specific case, probably not since it is a script tag, but in the general case it should be escaped.


>I still I don't know how to do that for, for example an attribute

I'm not sure what you mean here, do you mind sharing an example?

**Comment by finalclass** [comment]
Thx it works great with `Phoenix.HTML.raw`.
Regrading the attributes, it's all good. I got mistaken by something.
Can I quote you on stackoverflow or you would prefer to post there yourself?

**Comment by mhanberg** [comment]
Feel free to quote me!
